(()=>{"use strict";
const c=window.DPRO_CONFIG||{};
const api=async(path,options={})=>{const{timeoutMs=60000,signal,...fetchOptions}=options,isFormData=typeof FormData!=="undefined"&&fetchOptions.body instanceof FormData,controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.max(1000,Number(timeoutMs)||60000));if(signal){if(signal.aborted)controller.abort();else signal.addEventListener("abort",()=>controller.abort(),{once:true})}const headers={Accept:"application/json",...(fetchOptions.body&&!isFormData?{"Content-Type":"application/json"}:{}),...(fetchOptions.headers||{})};try{const r=await fetch(String(c.apiBase||"").replace(/\/$/,"")+path,{...fetchOptions,headers,signal:controller.signal,cache:fetchOptions.cache||((fetchOptions.method||"GET").toUpperCase()==="GET"?"no-store":"default")});const text=await r.text();let data={};if(text){try{data=JSON.parse(text)}catch{data={message:text.slice(0,1000)}}}if(!r.ok){const e=new Error(data.message||`通信に失敗しました。（HTTP ${r.status}）`);e.status=r.status;e.code=data.code;e.details=data.details;e.requestId=data.requestId||r.headers.get("x-request-id")||"";throw e}return data}catch(err){if(err?.name==="AbortError"){const e=new Error("通信がタイムアウトしました。電波状況を確認して、もう一度お試しください。");e.code="REQUEST_TIMEOUT";throw e}throw err}finally{clearTimeout(timer)}};
const esc=v=>String(v??"").replace(/[&<>'"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[ch]));
const fmt=d=>{if(!d)return"";const x=new Date(d);return Number.isNaN(x.getTime())?String(d):new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"short",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit"}).format(x)};
const fmtDate=d=>{if(!d)return"";const x=new Date(String(d)+"T00:00:00+09:00");return Number.isNaN(x.getTime())?String(d):new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"short",day:"numeric"}).format(x)};
const show=(el,type,message)=>{if(!el)return;el.className=`status show ${type}`;el.textContent=message;el.scrollIntoView({behavior:"smooth",block:"nearest"})};
const hide=el=>{if(!el)return;el.className="status";el.textContent=""};
const uuid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`;
const tokenKey="dpro_careplan_member_token",ownerTokenKey="dpro_careplan_owner_token";
window.DPRO={config:c,api,esc,fmt,fmtDate,show,hide,uuid,tokenKey,ownerTokenKey};
function addGuideEntry(){if(document.getElementById("dproGuideEntry")||new URLSearchParams(location.search).has("dpro_tutorial"))return;const a=document.createElement("a");a.id="dproGuideEntry";a.href="guide-center.html";a.textContent="？ 操作ガイド";a.setAttribute("aria-label","操作ガイドを開く");a.style.cssText="position:fixed;z-index:2147481000;right:max(12px,env(safe-area-inset-right));bottom:max(12px,env(safe-area-inset-bottom));display:inline-flex;align-items:center;justify-content:center;min-height:42px;max-width:calc(100vw - 24px);padding:8px 13px;border:1px solid rgba(255,255,255,.7);border-radius:999px;background:#082b45;color:#fff;text-decoration:none;font:800 12px -apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans JP',sans-serif;box-shadow:0 8px 24px rgba(8,43,69,.24);overflow-wrap:anywhere";a.addEventListener("focus",()=>{a.style.outline="3px solid rgba(15,118,110,.45)";a.style.outlineOffset="2px"});a.addEventListener("blur",()=>{a.style.outline="none"});document.body.appendChild(a)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",addGuideEntry,{once:true});else addGuideEntry();
})();
