(()=>{"use strict";
const D=window.DPRO,c=D.config,status=$("status"),loginPanel=$("loginPanel"),linkPanel=$("linkPanel"),portal=$("portal"),linkForm=$("linkForm"),messageForm=$("messageForm");
let currentToken=sessionStorage.getItem(D.tokenKey)||"",currentData=null;
function $(id){return document.getElementById(id)}
$("version").textContent=c.version||"";
document.querySelectorAll('input[name="actorType"]').forEach(x=>x.addEventListener("change",()=>$("birthField").classList.toggle("hidden",x.value!=="self"||!x.checked)));
$("showLink").addEventListener("click",()=>{loginPanel.classList.add("hidden");linkPanel.classList.remove("hidden");if(c.demo){$("clientCode").value="DEMO-CLIENT-001";$("applicantName").value="山田 美咲";$("linkPhone").value="090-3000-0001";$("linkRelationship").value="長女"}});
$("cancelLink").addEventListener("click",()=>{linkPanel.classList.add("hidden");loginPanel.classList.remove("hidden")});
$("demoLogin").addEventListener("click",()=>startSession({demoMemberCode:"DEMO-FAMILY-001"}));
$("logout").addEventListener("click",logout);$("lineLogin").addEventListener("click",lineLogin);linkForm.addEventListener("submit",submitLink);messageForm.addEventListener("submit",sendMessage);document.addEventListener("click",handleDocumentUpload);
if(currentToken)loadDashboard(currentToken);if(!c.demo&&c.liffId){$("demoActions").classList.add("hidden");$("lineLogin").classList.remove("hidden")}
async function lineLogin(){try{await liff.init({liffId:c.liffId});if(!liff.isLoggedIn()){liff.login();return}await startSession({idToken:liff.getIDToken()})}catch(err){D.show(status,"error",err.message||"LINEログインに失敗しました。")}}
async function startSession(body){D.hide(status);try{const data=await D.api("/member/session",{method:"POST",body:JSON.stringify(body)});currentToken=data.token;sessionStorage.setItem(D.tokenKey,currentToken);await loadDashboard(currentToken)}catch(err){D.show(status,"error",err.message)}}
async function submitLink(e){e.preventDefault();if(!$("linkConsent").checked){D.show(status,"error","同意欄を確認してください。");return}const actorType=linkForm.querySelector('input[name="actorType"]:checked')?.value||"",payload={actorType,clientCode:$("clientCode").value.trim(),applicantName:$("applicantName").value.trim(),phone:$("linkPhone").value.trim(),birthDate:$("birthDate").value,relationship:$("linkRelationship").value.trim()};if(c.demo)payload.demoLinkMode="pending";else{await liff.init({liffId:c.liffId});if(!liff.isLoggedIn()){liff.login();return}payload.idToken=liff.getIDToken()}try{const data=await D.api("/member/link-request",{method:"POST",body:JSON.stringify(payload)});D.show(status,"success",data.message);linkForm.querySelector("button[type=submit]").disabled=true}catch(err){D.show(status,"error",err.message)}}
async function loadDashboard(token){try{currentData=await D.api("/member/dashboard",{headers:{Authorization:`Bearer ${token}`}});render(currentData);loginPanel.classList.add("hidden");linkPanel.classList.add("hidden");portal.classList.remove("hidden");D.hide(status)}catch(err){sessionStorage.removeItem(D.tokenKey);currentToken="";portal.classList.add("hidden");loginPanel.classList.remove("hidden");D.show(status,"error",err.message)}}
function render(data){const p=data.profile||{};$("roleBadge").textContent=p.role==="family"?`ご家族（${p.relationship||"家族"}）`:"ご本人";$("actorName").textContent=p.actorName||"";$("clientName").textContent=`利用者：${p.clientName||""}（${p.clientCode||""}）`;$("careManager").textContent=`担当ケアマネ：${p.primaryCareManager||"確認中"}`;renderList("appointments",data.appointments||[],x=>`<div class="item"><div class="item-title">${D.esc(D.fmt(x.startsAt))}</div><div class="item-meta">${D.esc(x.purpose||x.type||"")}／${D.esc(x.location||"")}</div>${x.familyNote?`<div class="item-note">${D.esc(x.familyNote)}</div>`:""}</div>`,"今後の予定はありません。");renderDocuments(data.documentRequests||[],data.documentPermissions||data.permissions||{});renderList("messages",data.messages||[],x=>`<div class="item"><div class="item-title">${D.esc(x.subject||"事業所からの連絡")}</div><div class="item-meta">${D.esc(D.fmt(x.sentAt))}</div><div class="item-note">${D.esc(x.body)}</div></div>`,"新しい連絡はありません。");$("appointmentCount").textContent=`${(data.appointments||[]).length}件`;$("documentCount").textContent=`${(data.documentRequests||[]).length}件`;$("messageCount").textContent=`${(data.messages||[]).length}件`}
function renderDocuments(list,permissions){const max=Number(permissions.maxUploadBytes||10485760);$("documents").innerHTML=list.length?list.map(x=>{const docs=(x.documents||[]).map(d=>`<div class="item-note">提出済み：${D.esc(d.originalName)}（${formatBytes(d.sizeBytes)}／${statusLabel(d.status)}）</div>`).join("");const upload=x.canUpload?`<div class="field" style="margin-top:12px"><input class="control" type="file" id="file-${D.esc(x.id)}" accept=".pdf,.jpg,.jpeg,.png,.webp,.txt,.doc,.docx,.xls,.xlsx"><button class="btn primary" style="margin-top:8px" type="button" data-upload-document="${D.esc(x.id)}" data-max-bytes="${max}">この書類を提出する</button></div>`:"";return`<div class="item"><div class="item-title">${D.esc(x.title)}</div><div class="item-meta">期限：${D.esc(D.fmtDate(x.dueDate)||"指定なし")}／${statusLabel(x.status)}</div>${x.description?`<div class="item-note">${D.esc(x.description)}</div>`:""}${x.returnReason?`<div class="status show error" style="margin:10px 0 0">差戻し：${D.esc(x.returnReason)}</div>`:""}${docs}${upload}</div>`}).join(""):'<div class="empty">提出依頼はありません。</div>'}
function statusLabel(v){return({requested:"提出待ち",viewed:"確認済み",uploaded:"送信済み",received:"確認待ち",accepted:"受領済み",returned:"再提出依頼",cancelled:"取消",rejected:"差戻し"})[v]||D.esc(v||"")}
function formatBytes(v){const n=Number(v||0);return n>=1048576?`${(n/1048576).toFixed(1)}MB`:n>=1024?`${Math.round(n/1024)}KB`:`${n}B`}
function renderList(id,list,fn,empty){$(id).innerHTML=list.length?list.map(fn).join(""):`<div class="empty">${D.esc(empty)}</div>`}
async function handleDocumentUpload(e){const button=e.target.closest("[data-upload-document]");if(!button)return;const requestId=button.dataset.uploadDocument,input=$(`file-${requestId}`),file=input?.files?.[0],max=Number(button.dataset.maxBytes||10485760);if(!file){D.show(status,"error","提出するファイルを選択してください。");return}if(file.size>max){D.show(status,"error",`ファイルは${formatBytes(max)}以下にしてください。`);return}button.disabled=true;const original=button.textContent;button.textContent="送信中…";try{const form=new FormData();form.append("documentRequestId",requestId);form.append("file",file,file.name);const data=await D.api("/member/documents/upload",{method:"POST",headers:{Authorization:`Bearer ${currentToken}`,"X-Idempotency-Key":D.uuid()},body:form});D.show(status,"success",data.message||"書類を提出しました。");await loadDashboard(currentToken)}catch(err){D.show(status,"error",err.message)}finally{button.disabled=false;button.textContent=original}}
async function sendMessage(e){e.preventDefault();const subject=$("messageSubject").value.trim(),body=$("messageBody").value.trim(),button=$("sendMessage");if(!currentToken||!body){D.show(status,"error","連絡内容を入力してください。");return}button.disabled=true;try{const data=await D.api("/member/messages",{method:"POST",headers:{Authorization:`Bearer ${currentToken}`,"X-Idempotency-Key":D.uuid()},body:JSON.stringify({subject,body})});messageForm.reset();D.show(status,"success",data.message)}catch(err){D.show(status,"error",err.message)}finally{button.disabled=false}}
async function logout(){try{if(currentToken)await D.api("/member/logout",{method:"POST",headers:{Authorization:`Bearer ${currentToken}`}})}catch{}sessionStorage.removeItem(D.tokenKey);currentToken="";portal.classList.add("hidden");loginPanel.classList.remove("hidden");D.show(status,"info","ログアウトしました。")}
})();