(()=>{"use strict";
const D=window.DPRO,c=D.config,statusEl=document.getElementById("status"),loginPanel=document.getElementById("loginPanel"),appPanel=document.getElementById("appPanel");
let token=sessionStorage.getItem(D.ownerTokenKey)||"",dashboard=null,intakes=[],clients=[],documents=[],current=null;
const $=id=>document.getElementById(id),safe=v=>D.esc(v??""),authHeaders=()=>({Authorization:`Bearer ${token}`});
const careLabels={independent:"自立",support_1:"要支援1",support_2:"要支援2",care_1:"要介護1",care_2:"要介護2",care_3:"要介護3",care_4:"要介護4",care_5:"要介護5",pending:"申請中",unknown:"未設定"};
const clientStatusLabels={prospective:"相談中",active:"利用中",hospitalized:"入院中",suspended:"休止中",ended:"終了",deceased:"死亡"};
const intakeStatusLabels={new:"新規",contacting:"連絡中",interview_scheduled:"面談予定",assessing:"アセスメント中",contracted:"契約済み",declined:"辞退",closed:"終了"};
const planStatusLabels={draft:"下書き",assessment:"アセスメント",service_meeting:"担当者会議",consent_pending:"同意待ち",active:"有効",review_due:"見直し",closed:"終了",cancelled:"取消"};
const roleLabels={manager:"管理者",chief_care_manager:"主任ケアマネ",care_manager:"ケアマネ"};
const meetingStatusLabels={planning:"調整中",inviting:"案内中",scheduled:"開催予定",held:"開催済み",completed:"記録完了",cancelled:"中止"};
const certStatusLabels={pending:"申請中",current:"有効",expired:"期限切れ",withdrawn:"取下げ"};

$("version").textContent=c.version||"";
$("organizationCode").value=c.organizationCode||"";
fillStaticSelects();
bindEvents();
if(token)restore();

function fillStaticSelects(){
  const careOptions=Object.entries(careLabels).map(([v,l])=>`<option value="${v}">${l}</option>`).join("");
  $("clientCareLevel").innerHTML=careOptions;$("certCareLevel").innerHTML=careOptions;
  $("clientStatusValue").innerHTML=Object.entries(clientStatusLabels).map(([v,l])=>`<option value="${v}">${l}</option>`).join("");
  $("planStatus").innerHTML=Object.entries(planStatusLabels).map(([v,l])=>`<option value="${v}">${l}</option>`).join("");
}
function bindEvents(){
  $("clearCode").addEventListener("click",()=>{$("accessCode").value="";$("accessCode").focus()});
  $("demoFill").addEventListener("click",()=>{$("organizationCode").value="dpro_careplan_demo";$("staffCode").value="DEMO-MANAGER";$("accessCode").value="1234"});
  $("loginForm").addEventListener("submit",login);$("logout").addEventListener("click",logout);$("refreshAll").addEventListener("click",refreshAll);
  document.querySelectorAll(".owner-nav [data-view]").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));
  $("intakeSearchForm").addEventListener("submit",e=>{e.preventDefault();loadIntakes()});$("clearIntakeSearch").addEventListener("click",()=>{$("intakeSearch").value="";$("intakeStatus").value="";loadIntakes()});
  $("clientSearchForm").addEventListener("submit",e=>{e.preventDefault();loadClients()});$("clearClientSearch").addEventListener("click",()=>{$("clientSearch").value="";$("clientStatus").value="";loadClients()});
  $("newClientButton").addEventListener("click",openNewClient);$("backClients").addEventListener("click",()=>switchView("clients"));
  $("editClientButton").addEventListener("click",()=>toggle("clientForm",true));$("cancelClientEdit").addEventListener("click",()=>toggle("clientForm",false));$("clientForm").addEventListener("submit",saveClient);
  $("assignmentForm").addEventListener("submit",saveAssignment);
  $("newCertification").addEventListener("click",()=>openCertification());$("cancelCertification").addEventListener("click",()=>toggle("certificationForm",false));$("certificationForm").addEventListener("submit",saveCertification);
  $("newPlan").addEventListener("click",()=>openPlan());$("cancelPlan").addEventListener("click",()=>toggle("planForm",false));$("planForm").addEventListener("submit",savePlan);
  $("newMeeting").addEventListener("click",()=>openMeeting());$("cancelMeeting").addEventListener("click",()=>toggle("meetingForm",false));$("meetingForm").addEventListener("submit",saveMeeting);
  $("documentRequestForm").addEventListener("submit",saveDocumentRequest);
  $("documentSearchForm").addEventListener("submit",e=>{e.preventDefault();loadDocuments()});
  $("reloadDocuments").addEventListener("click",loadDocuments);
  $("runSystemCheck").addEventListener("click",runSystemCheck);
  document.addEventListener("click",handleDelegatedClick);
}
function toggle(id,on){$(id).classList.toggle("hidden",!on)}
function label(map,v){return map[v]||v||"-"}
function isoInput(v){if(!v)return"";const d=new Date(v);if(Number.isNaN(d.getTime()))return"";const parts=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(d).reduce((o,p)=>(o[p.type]=p.value,o),{});return`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`}
function today(){return new Date().toLocaleDateString("sv-SE",{timeZone:"Asia/Tokyo"})}
function infoRows(rows){return`<dl class="info-table">${rows.map(([k,v])=>`<div class="info-row"><dt>${safe(k)}</dt><dd>${safe(v||"-")}</dd></div>`).join("")}</dl>`}

async function login(e){e.preventDefault();const b=$("loginButton");b.disabled=true;try{const data=await D.api("/owner/login",{method:"POST",body:JSON.stringify({organizationCode:$("organizationCode").value.trim(),staffCode:$("staffCode").value.trim(),accessCode:$("accessCode").value})});token=data.token;sessionStorage.setItem(D.ownerTokenKey,token);showApp(data);await refreshAll();D.hide(statusEl)}catch(err){D.show(statusEl,"error",err.message)}finally{b.disabled=false}}
async function restore(){try{const data=await D.api("/auth/me",{headers:authHeaders()});if(!["manager","chief_care_manager"].includes(data.staff?.role_type))throw new Error("管理者権限が必要です。");showApp(data);await refreshAll()}catch(err){sessionStorage.removeItem(D.ownerTokenKey);token="";D.show(statusEl,"error",err.message||"ログインし直してください。")}}
function showApp(data){const s=data.staff||{},o=data.organization||{};$("ownerName").textContent=s.full_name||s.fullName||"";$("ownerMeta").textContent=`${label(roleLabels,s.role_type||s.roleType)}／${s.staff_code||s.staffCode||""}`;$("organizationName").textContent=o.organization_name||o.organizationName||"";loginPanel.classList.add("hidden");appPanel.classList.remove("hidden");$("todayLabel").textContent=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",dateStyle:"full"}).format(new Date())}
async function logout(){try{await D.api("/auth/logout",{method:"POST",headers:authHeaders()})}catch{}sessionStorage.removeItem(D.ownerTokenKey);token="";location.reload()}
async function refreshAll(){try{await Promise.all([loadDashboard(),loadIntakes(),loadClients(),loadLinkRequests(),loadDocuments()]);if(current?.client?.id)await openClient(current.client.id,false);D.hide(statusEl)}catch(err){D.show(statusEl,"error",err.message)}}

function switchView(name){document.querySelectorAll(".owner-view").forEach(v=>v.classList.add("hidden"));document.querySelectorAll(".owner-nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===name));const map={dashboard:"viewDashboard",intakes:"viewIntakes",clients:"viewClients",links:"viewLinks",monitoring:"viewMonitoring",documents:"viewDocuments",system:"viewSystem"};$(map[name]||"viewDashboard").classList.remove("hidden");if(name==="monitoring")renderMonitoringReviews();if(name==="documents")renderDocuments();if(name==="system")runSystemCheck()}

async function loadDashboard(){dashboard=await D.api("/owner/dashboard",{headers:authHeaders()});renderDashboard()}
function renderDashboard(){const s=dashboard.summary||{};const cards=[[s.activeClients||0,"利用中"],[s.prospectiveClients||0,"相談中"],[s.newIntakes||0,"未完了相談","attention"],[s.pendingLinks||0,"LINE承認待ち","attention"],[s.certificationDue||0,"認定期限90日内","critical"],[s.planDue||0,"計画見直し30日内","attention"],[s.monitoringReview||0,"記録確認待ち","attention"],[s.documentDue||0,"書類期限14日内","attention"],[s.todayAppointments||0,"本日の予定"],[s.openAlerts||0,"未解決警告","critical"]];$("summaryGrid").innerHTML=cards.map(([n,t,c])=>`<div class="owner-summary-card ${c||""}"><b>${safe(n)}</b><span>${safe(t)}</span></div>`).join("");
  $("staffWorkload").innerHTML=(dashboard.staffWorkload||[]).length?(dashboard.staffWorkload||[]).map(x=>`<div class="workload-row"><b>${safe(x.fullName)}<small class="muted">${safe(label(roleLabels,x.roleType))}</small></b><span class="metric-pill">担当<br>${safe(x.primaryClients)}</span><span class="metric-pill">タスク<br>${safe(x.openTasks)}</span><span class="metric-pill">本日<br>${safe(x.todayAppointments)}</span></div>`).join(""):'<div class="empty-small">職員情報がありません。</div>';
  $("deadlineList").innerHTML=(dashboard.deadlines||[]).length?(dashboard.deadlines||[]).map(x=>`<button class="deadline-row text-card" type="button" data-client="${safe(x.clientId)}"><span><strong>${safe(x.clientName)}</strong><small>${safe(x.clientCode)}／${safe(x.primaryStaffName||"担当未設定")}／${safe(label(careLabels,x.careLevel))}</small></span><span class="deadline-date">${x.certificationValidTo?`認定 ${safe(D.fmtDate(x.certificationValidTo))}`:""}${x.nextReviewDue?`<br>見直し ${safe(D.fmtDate(x.nextReviewDue))}`:""}</span></button>`).join(""):'<div class="empty-small">期限が近い利用者はいません。</div>';
  $("recentIntakeList").innerHTML=(dashboard.recentIntakes||[]).length?(dashboard.recentIntakes||[]).map(x=>`<div class="timeline-item"><div class="timeline-title">${safe(x.applicantName)}／${safe(label(intakeStatusLabels,x.status))}</div><div class="timeline-meta">${safe(x.phone||"")}／${safe(x.assignedStaffName||"担当未設定")}</div><div>${safe((x.inquirySummary||"").slice(0,100))}</div></div>`).join(""):'<div class="empty-small">相談受付はありません。</div>';
  $("upcomingMeetingList").innerHTML=(dashboard.upcomingMeetings||[]).length?(dashboard.upcomingMeetings||[]).map(x=>`<button class="timeline-item text-card" type="button" data-client="${safe(x.clientId)}"><div class="timeline-title">${safe(x.clientName)}／${safe(label(meetingStatusLabels,x.status))}</div><div class="timeline-meta">${safe(x.scheduledStart?D.fmt(x.scheduledStart):"日時調整中")} ${safe(x.location||"")}</div></button>`).join(""):'<div class="empty-small">今後の担当者会議はありません。</div>';
  renderMonitoringReviews();
}

async function loadIntakes(){if(!token)return;const q=$("intakeSearch").value.trim(),st=$("intakeStatus").value;const data=await D.api(`/owner/intakes?status=${encodeURIComponent(st)}&q=${encodeURIComponent(q)}`,{headers:authHeaders()});intakes=data.intakes||[];renderIntakes()}
function staffOptions(selected){return`<option value="">担当未設定</option>${(dashboard?.staffWorkload||[]).map(s=>`<option value="${safe(s.id)}" ${s.id===selected?"selected":""}>${safe(s.fullName)}</option>`).join("")}`}
function renderIntakes(){$("intakeList").innerHTML=intakes.length?intakes.map(i=>`<article class="management-item"><div class="management-head"><div><div class="management-title">${safe(i.applicantName)} <span class="badge">${safe(label(intakeStatusLabels,i.status))}</span></div><div class="management-meta">${safe(i.intakeCode)}／${safe(i.phone||"電話なし")}／${safe(i.relationship||label({self:"本人",family:"家族",provider:"関係者",other:"その他"},i.applicantType))}</div></div><small>${safe(D.fmt(i.createdAt))}</small></div><div class="management-body">${safe(i.inquirySummary)}</div><div class="management-actions"><select class="control" data-intake-status="${safe(i.id)}">${Object.entries(intakeStatusLabels).map(([v,l])=>`<option value="${v}" ${v===i.status?"selected":""}>${l}</option>`).join("")}</select><select class="control" data-intake-staff="${safe(i.id)}">${staffOptions(i.assignedStaffId)}</select><input class="control" data-intake-close="${safe(i.id)}" placeholder="終了理由（辞退・終了時）" value="${safe(i.closeReason||"")}"><button class="mini-btn primary" type="button" data-intake-save="${safe(i.id)}" data-current-status="${safe(i.status)}">保存</button></div></article>`).join(""):'<div class="empty">該当する相談受付はありません。</div>'}

async function loadClients(){if(!token)return;const q=$("clientSearch").value.trim(),st=$("clientStatus").value;const data=await D.api(`/owner/clients?status=${encodeURIComponent(st)}&q=${encodeURIComponent(q)}`,{headers:authHeaders()});clients=data.clients||[];renderClients()}
function renderClients(){$("clientList").innerHTML=clients.length?clients.map(x=>`<button class="client-ledger-card" type="button" data-client="${safe(x.id)}"><span class="client-ledger-code">${safe(x.clientCode)}</span><span class="client-ledger-name">${safe(x.fullName)}</span><span class="client-ledger-data"><span>${safe(label(clientStatusLabels,x.status))}／${safe(label(careLabels,x.careLevel))}</span><span>担当：${safe(x.primaryStaffName||"未設定")}</span><span>認定期限：${safe(x.certificationValidTo?D.fmtDate(x.certificationValidTo):"未設定")}</span><span>計画：${safe(label(planStatusLabels,x.planStatus||"未設定"))}／見直し ${safe(x.nextReviewDue?D.fmtDate(x.nextReviewDue):"未設定")}</span><span>未完了書類：${safe(x.pendingDocuments||0)}件</span></span></button>`).join(""):'<div class="empty">該当する利用者はいません。</div>'}
function openNewClient(){current={client:{id:null,clientCode:"",fullName:"",fullNameKana:"",birthDate:"",gender:"",phone:"",postalCode:"",address:"",preferredContactMethod:"phone",careLevel:"unknown",insurerName:"",primaryMedicalInstitution:"",emergencySummary:"",familyPublicNote:"",internalNotes:"",status:"prospective",version:null},assignments:[],familyContacts:[],certifications:[],planCycles:[],meetings:[],monitoringRecords:[],documentRequests:[],staffList:dashboard?.staffWorkload||[]};renderClientDetail();toggle("clientForm",true);switchClientDetail()}
async function openClient(id,switchIt=true){try{current=await D.api(`/owner/clients/${id}`,{headers:authHeaders()});renderClientDetail();if(switchIt)switchClientDetail()}catch(err){D.show(statusEl,"error",err.message)}}
function switchClientDetail(){document.querySelectorAll(".owner-view").forEach(v=>v.classList.add("hidden"));$("viewClientDetail").classList.remove("hidden");document.querySelectorAll(".owner-nav button").forEach(b=>b.classList.remove("active"))}
function renderClientDetail(){const c=current.client||{};$("detailClientName").textContent=c.fullName||"新規利用者";$("detailClientMeta").textContent=c.id?`${c.clientCode}／${label(clientStatusLabels,c.status)}／version ${c.version}`:"基本情報を入力して保存してください。";$("detailCareBadge").textContent=label(careLabels,c.careLevel||"unknown");$("clientSafety").textContent=c.emergencySummary||"";$("clientSafety").classList.toggle("hidden",!c.emergencySummary);
  $("clientBasicDisplay").innerHTML=infoRows([["氏名",c.fullName],["氏名カナ",c.fullNameKana],["生年月日",c.birthDate?D.fmtDate(c.birthDate):""],["電話",c.phone],["住所",c.address],["状態",label(clientStatusLabels,c.status)],["要介護度",label(careLabels,c.careLevel)],["保険者",c.insurerName],["主治医・医療機関",c.primaryMedicalInstitution],["家族公開メモ",c.familyPublicNote],["内部メモ",c.internalNotes]]);
  fillClientForm(c);renderAssignments();renderCertifications();renderPlans();renderMeetings();renderDocuments();renderClientMonitoring();fillClientSelects();disableDependentForms(!c.id)}
function fillClientForm(c){$("clientId").value=c.id||"";$("clientExpectedVersion").value=c.version||"";$("clientCode").value=c.clientCode||"";$("clientCode").disabled=Boolean(c.id);$("clientFullName").value=c.fullName||"";$("clientFullNameKana").value=c.fullNameKana||"";$("clientBirthDate").value=c.birthDate||"";$("clientGender").value=c.gender||"";$("clientPhone").value=c.phone||"";$("clientPostalCode").value=c.postalCode||"";$("clientAddress").value=c.address||"";$("clientContactMethod").value=c.preferredContactMethod||"phone";$("clientCareLevel").value=c.careLevel||"unknown";$("clientStatusValue").value=c.status||"prospective";$("clientInsurerName").value=c.insurerName||"";$("clientMedical").value=c.primaryMedicalInstitution||"";$("clientEmergency").value=c.emergencySummary||"";$("clientFamilyNote").value=c.familyPublicNote||"";$("clientInternalNotes").value=c.internalNotes||""}
function disableDependentForms(disabled){["assignmentForm","certificationForm","planForm","meetingForm","documentRequestForm"].forEach(id=>$(id).querySelectorAll("input,select,textarea,button").forEach(el=>el.disabled=disabled));["newCertification","newPlan","newMeeting"].forEach(id=>$(id).disabled=disabled)}
function fillClientSelects(){const staff=current.staffList?.length?current.staffList:(dashboard?.staffWorkload||[]);$("assignmentStaff").innerHTML=`<option value="">選択してください</option>${staff.map(s=>`<option value="${safe(s.id)}">${safe(s.fullName)}／${safe(label(roleLabels,s.roleType))}</option>`).join("")}`;$("assignmentStart").value=today();$("documentFamily").innerHTML=`<option value="">本人・家族共通</option>${(current.familyContacts||[]).filter(f=>f.isActive!==false).map(f=>`<option value="${safe(f.id)}">${safe(f.fullName)}（${safe(f.relationship)}）</option>`).join("")}`;$("planCertification").innerHTML=`<option value="">未選択</option>${(current.certifications||[]).map(x=>`<option value="${safe(x.id)}">${safe(label(careLabels,x.careLevel))}／${safe(D.fmtDate(x.validFrom))}～${safe(D.fmtDate(x.validTo))}</option>`).join("")}`;$("meetingPlan").innerHTML=`<option value="">未選択</option>${(current.planCycles||[]).map(x=>`<option value="${safe(x.id)}">${safe(label(planStatusLabels,x.status))}／${safe(D.fmtDate(x.periodStart))}</option>`).join("")}`}
function renderAssignments(){$("assignmentList").innerHTML=(current.assignments||[]).length?(current.assignments||[]).map(x=>`<div class="timeline-item"><div class="timeline-title">${safe(x.staffName)}／${safe(label({primary:"主担当",secondary:"副担当",supervisor:"主任確認"},x.assignmentRole))}</div><div class="timeline-meta">${safe(D.fmtDate(x.startDate))}${x.endDate?`～${safe(D.fmtDate(x.endDate))}`:""}／${x.isCurrent?"現在":"終了"}</div></div>`).join(""):'<div class="empty-small">担当設定はありません。</div>'}
function renderCertifications(){$("certificationList").innerHTML=(current.certifications||[]).length?(current.certifications||[]).map(x=>`<div class="timeline-item"><div class="timeline-title">${safe(label(careLabels,x.careLevel))}／${safe(label(certStatusLabels,x.status))}</div><div class="timeline-meta">${safe(D.fmtDate(x.validFrom))} ～ ${safe(D.fmtDate(x.validTo))}／${safe(x.insurerName||"")}</div><button class="mini-btn" type="button" data-edit-cert="${safe(x.id)}">編集</button></div>`).join(""):'<div class="empty-small">認定情報はありません。</div>'}
function renderPlans(){$("planList").innerHTML=(current.planCycles||[]).length?(current.planCycles||[]).map(x=>`<div class="timeline-item"><div class="timeline-title">${safe(label(planStatusLabels,x.status))}／${safe(label({initial:"初回",renewal:"更新",change:"変更",provisional:"暫定"},x.planType))}</div><div class="timeline-meta">${safe(D.fmtDate(x.periodStart))}${x.periodEnd?` ～ ${safe(D.fmtDate(x.periodEnd))}`:""}／見直し ${safe(x.nextReviewDue?D.fmtDate(x.nextReviewDue):"未設定")}</div><button class="mini-btn" type="button" data-edit-plan="${safe(x.id)}">編集</button></div>`).join(""):'<div class="empty-small">ケアプランはありません。</div>'}
function renderMeetings(){$("meetingList").innerHTML=(current.meetings||[]).length?(current.meetings||[]).map(x=>`<div class="timeline-item"><div class="timeline-title">${safe(label(meetingStatusLabels,x.status))}／${safe(x.scheduledStart?D.fmt(x.scheduledStart):"日時未定")}</div><div class="timeline-meta">${safe(x.location||"")}／参加者 ${safe((x.participants||[]).length)}名</div><button class="mini-btn" type="button" data-edit-meeting="${safe(x.id)}">編集</button></div>`).join(""):'<div class="empty-small">担当者会議はありません。</div>'}
function renderDocuments(){$("documentRequestList").innerHTML=(current.documentRequests||[]).length?(current.documentRequests||[]).map(x=>`<div class="timeline-item"><div class="timeline-title">${safe(x.title)}／${safe(x.status)}</div><div class="timeline-meta">期限 ${safe(x.dueDate?D.fmtDate(x.dueDate):"未設定")}／家族表示 ${x.familyVisible?"あり":"なし"}</div></div>`).join(""):'<div class="empty-small">書類依頼はありません。</div>'}
function renderClientMonitoring(){$("clientMonitoringList").innerHTML=(current.monitoringRecords||[]).length?(current.monitoringRecords||[]).map(x=>`<div class="timeline-item"><div class="timeline-title">${safe(D.fmtDate(x.monitoringMonth))}／${safe(x.staffName)}／${safe(x.status)}</div><div class="timeline-meta">${safe((x.conditionSummary||"").slice(0,100))}</div>${x.returnReason?`<div class="item-note">差戻し：${safe(x.returnReason)}</div>`:""}</div>`).join(""):'<div class="empty-small">モニタリング記録はありません。</div>'}

async function saveClient(e){e.preventDefault();const id=$("clientId").value;try{const data=await D.api(id?`/owner/clients/${id}`:"/owner/clients",{method:"POST",headers:authHeaders(),body:JSON.stringify({expectedVersion:$("clientExpectedVersion").value,clientCode:$("clientCode").value,fullName:$("clientFullName").value,fullNameKana:$("clientFullNameKana").value,birthDate:$("clientBirthDate").value,gender:$("clientGender").value,phone:$("clientPhone").value,postalCode:$("clientPostalCode").value,address:$("clientAddress").value,preferredContactMethod:$("clientContactMethod").value,careLevel:$("clientCareLevel").value,insurerName:$("clientInsurerName").value,primaryMedicalInstitution:$("clientMedical").value,emergencySummary:$("clientEmergency").value,familyPublicNote:$("clientFamilyNote").value,internalNotes:$("clientInternalNotes").value,status:$("clientStatusValue").value})});await loadClients();await openClient(data.id,false);toggle("clientForm",false);D.show(statusEl,"success",id?"利用者情報を更新しました。":"利用者を登録しました。")}catch(err){D.show(statusEl,"error",err.message)}}
async function saveAssignment(e){e.preventDefault();if(!current?.client?.id)return;try{await D.api("/owner/assignments",{method:"POST",headers:authHeaders(),body:JSON.stringify({clientId:current.client.id,staffId:$("assignmentStaff").value,assignmentRole:$("assignmentRole").value,startDate:$("assignmentStart").value,note:$("assignmentNote").value})});await openClient(current.client.id,false);await loadDashboard();D.show(statusEl,"success","担当を設定しました。")}catch(err){D.show(statusEl,"error",err.message)}}

function openCertification(id=null){const x=id?(current.certifications||[]).find(v=>v.id===id):null;$("certificationId").value=x?.id||"";$("certificationExpectedUpdatedAt").value=x?.updatedAt||"";$("certCareLevel").value=x?.careLevel||current.client.careLevel||"unknown";$("certStatus").value=x?.status||"current";$("certValidFrom").value=x?.validFrom||"";$("certValidTo").value=x?.validTo||"";$("certDate").value=x?.certificationDate||"";$("certInsurer").value=x?.insurerName||current.client.insurerName||"";$("certInternalNote").value=x?.internalNote||"";toggle("certificationForm",true)}
async function saveCertification(e){e.preventDefault();try{await D.api("/owner/certifications",{method:"POST",headers:authHeaders(),body:JSON.stringify({clientId:current.client.id,certificationId:$("certificationId").value,expectedUpdatedAt:$("certificationExpectedUpdatedAt").value,careLevel:$("certCareLevel").value,insurerName:$("certInsurer").value,validFrom:$("certValidFrom").value,validTo:$("certValidTo").value,certificationDate:$("certDate").value,status:$("certStatus").value,internalNote:$("certInternalNote").value})});await openClient(current.client.id,false);toggle("certificationForm",false);await loadDashboard();D.show(statusEl,"success","認定情報を保存しました。")}catch(err){D.show(statusEl,"error",err.message)}}

function openPlan(id=null){const x=id?(current.planCycles||[]).find(v=>v.id===id):null;$("planId").value=x?.id||"";$("planExpectedVersion").value=x?.version||"";$("planType").value=x?.planType||"initial";$("planStatus").value=x?.status||"draft";$("planCertification").value=x?.certificationId||"";$("planReviewDue").value=x?.nextReviewDue||"";$("planPeriodStart").value=x?.periodStart||today();$("planPeriodEnd").value=x?.periodEnd||"";$("planAssessmentAt").value=isoInput(x?.assessmentCompletedAt);$("planDraftAt").value=isoInput(x?.draftCompletedAt);$("planMeetingAt").value=isoInput(x?.meetingCompletedAt);$("planConsentAt").value=isoInput(x?.consentRecordedAt);$("planDeliveredAt").value=isoInput(x?.deliveredAt);$("planInternalNote").value=x?.internalNote||"";$("planFamilySummary").value=x?.familyPublicSummary||"";toggle("planForm",true)}
async function savePlan(e){e.preventDefault();try{await D.api("/owner/plan-cycles",{method:"POST",headers:authHeaders(),body:JSON.stringify({clientId:current.client.id,planCycleId:$("planId").value,expectedVersion:$("planExpectedVersion").value,certificationId:$("planCertification").value,planType:$("planType").value,periodStart:$("planPeriodStart").value,periodEnd:$("planPeriodEnd").value,status:$("planStatus").value,assessmentCompletedAt:$("planAssessmentAt").value,draftCompletedAt:$("planDraftAt").value,meetingCompletedAt:$("planMeetingAt").value,consentRecordedAt:$("planConsentAt").value,deliveredAt:$("planDeliveredAt").value,nextReviewDue:$("planReviewDue").value,internalNote:$("planInternalNote").value,familyPublicSummary:$("planFamilySummary").value})});await openClient(current.client.id,false);toggle("planForm",false);await loadDashboard();D.show(statusEl,"success","ケアプランを保存しました。")}catch(err){D.show(statusEl,"error",err.message)}}

function openMeeting(id=null){const x=id?(current.meetings||[]).find(v=>v.id===id):null;$("meetingId").value=x?.id||"";$("meetingExpectedUpdatedAt").value=x?.updatedAt||"";$("meetingPlan").value=x?.planCycleId||"";$("meetingStatus").value=x?.status||"planning";$("meetingStart").value=isoInput(x?.scheduledStart);$("meetingEnd").value=isoInput(x?.scheduledEnd);$("meetingFormat").value=x?.meetingFormat||"in_person";$("meetingLocation").value=x?.location||"";$("meetingParticipants").value=(x?.participants||[]).map(v=>typeof v==="string"?v:(v.name||JSON.stringify(v))).join("\n");$("meetingAgenda").value=x?.agenda||"";$("meetingInternalSummary").value=x?.summaryInternal||"";$("meetingFamilySummary").value=x?.familyPublicSummary||"";$("meetingConsent").checked=Boolean(x?.consentConfirmed);toggle("meetingForm",true)}
async function saveMeeting(e){e.preventDefault();try{await D.api("/owner/service-meetings",{method:"POST",headers:authHeaders(),body:JSON.stringify({clientId:current.client.id,meetingId:$("meetingId").value,expectedUpdatedAt:$("meetingExpectedUpdatedAt").value,planCycleId:$("meetingPlan").value,scheduledStart:$("meetingStart").value,scheduledEnd:$("meetingEnd").value,meetingFormat:$("meetingFormat").value,location:$("meetingLocation").value,status:$("meetingStatus").value,participants:$("meetingParticipants").value.split(/\n+/).map(v=>v.trim()).filter(Boolean),agenda:$("meetingAgenda").value,summaryInternal:$("meetingInternalSummary").value,familyPublicSummary:$("meetingFamilySummary").value,consentConfirmed:$("meetingConsent").checked})});await openClient(current.client.id,false);toggle("meetingForm",false);await loadDashboard();D.show(statusEl,"success","担当者会議を保存しました。")}catch(err){D.show(statusEl,"error",err.message)}}

async function saveDocumentRequest(e){e.preventDefault();try{await D.api("/owner/document-requests",{method:"POST",headers:{...authHeaders(),"X-Idempotency-Key":D.uuid()},body:JSON.stringify({clientId:current.client.id,familyContactId:$("documentFamily").value,category:$("documentCategory").value,title:$("documentTitle").value,description:$("documentDescription").value,dueDate:$("documentDueDate").value,familyVisible:$("documentFamilyVisible").checked})});e.target.reset();$("documentFamilyVisible").checked=true;await openClient(current.client.id,false);D.show(statusEl,"success","書類依頼を登録しました。")}catch(err){D.show(statusEl,"error",err.message)}}

async function loadDocuments(){if(!token)return;const st=$("documentStatusFilter")?.value||"";const data=await D.api(`/owner/documents${st?`?status=${encodeURIComponent(st)}`:""}`,{headers:authHeaders()});documents=data.documents||[];renderDocuments()}
function renderDocuments(){const el=$("ownerDocumentList");if(!el)return;el.innerHTML=documents.length?documents.map(x=>`<article class="management-item document-review-card"><div class="management-head"><div><div class="management-title">${safe(x.clientName)}／${safe(x.requestTitle||"提出書類")}</div><div class="management-meta">${safe(x.originalName)}／${formatBytes(x.sizeBytes)}／${safe(x.mimeType)}／${safe(documentStatusLabel(x.status,x.requestStatus))}</div></div><small>${safe(D.fmt(x.createdAt))}</small></div>${x.returnReason?`<div class="item-note">差戻し理由：${safe(x.returnReason)}</div>`:""}<div class="management-actions"><button class="mini-btn" type="button" data-document-download="${safe(x.id)}" data-document-name="${safe(x.originalName)}">ダウンロード</button>${x.status==="uploaded"&&x.requestStatus==="received"?`<button class="mini-btn primary" type="button" data-document-review="${safe(x.id)}" data-decision="accepted" data-updated-at="${safe(x.updatedAt)}">受領</button><button class="mini-btn danger" type="button" data-document-review="${safe(x.id)}" data-decision="returned" data-updated-at="${safe(x.updatedAt)}">差戻し</button>`:""}</div><textarea class="control compact" data-document-reason="${safe(x.id)}" placeholder="差戻し理由（差戻し時は必須）"></textarea></article>`).join(""):'<div class="empty">該当する提出書類はありません。</div>'}
function documentStatusLabel(doc,req){if(req==="returned"||doc==="rejected")return"差戻し";return({uploaded:"未確認",accepted:"受領済み",deleted:"削除"})[doc]||doc||req||"-"}
function formatBytes(v){const n=Number(v||0);return n>=1048576?`${(n/1048576).toFixed(1)}MB`:n>=1024?`${Math.round(n/1024)}KB`:`${n}B`}
async function reviewDocument(btn){const id=btn.dataset.documentReview,decision=btn.dataset.decision,reason=document.querySelector(`[data-document-reason="${id}"]`)?.value.trim()||"";if(decision==="returned"&&!reason){D.show(statusEl,"error","差戻し理由を入力してください。");return}if(!confirm(decision==="accepted"?"この書類を受領しますか。":"この書類を差し戻しますか。"))return;btn.disabled=true;try{await D.api(`/owner/documents/${id}/review`,{method:"POST",headers:authHeaders(),body:JSON.stringify({decision,returnReason:reason,expectedUpdatedAt:btn.dataset.updatedAt})});await Promise.all([loadDocuments(),loadDashboard()]);D.show(statusEl,"success",decision==="accepted"?"書類を受領しました。":"書類を差し戻しました。")}catch(err){D.show(statusEl,"error",err.message)}finally{btn.disabled=false}}
async function downloadDocument(btn){btn.disabled=true;try{const response=await fetch(`${String(c.apiBase).replace(/\/$/,"")}/owner/documents/${btn.dataset.documentDownload}/download`,{headers:authHeaders()});if(!response.ok){let data={};try{data=await response.json()}catch{}throw new Error(data.message||"ファイルを取得できませんでした。")}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=btn.dataset.documentName||"document";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(err){D.show(statusEl,"error",err.message)}finally{btn.disabled=false}}

async function loadLinkRequests(){if(!token)return;const data=await D.api("/owner/link-requests?status=pending",{headers:authHeaders()});if(dashboard)dashboard.pendingLinks=data.requests||[];renderLinkRequests()}
function renderLinkRequests(){const items=dashboard?.pendingLinks||[];$("linkRequestList").innerHTML=items.length?items.map(x=>`<article class="management-item"><div class="management-head"><div><div class="management-title">${safe(x.applicantName)}／${safe(x.clientName||"利用者未確定")}</div><div class="management-meta">${safe(x.requestCode)}／${safe(x.relationship||"本人")}／${safe(x.phone||"")}</div></div><small>${safe(D.fmt(x.createdAt))}</small></div><textarea class="control compact" data-link-note="${safe(x.id)}" placeholder="確認メモ"></textarea><div class="management-actions"><button class="mini-btn primary" type="button" data-link-decision="${safe(x.id)}" data-decision="approved">承認</button><button class="mini-btn danger" type="button" data-link-decision="${safe(x.id)}" data-decision="rejected">却下</button></div></article>`).join(""):'<div class="empty">承認待ちのLINE連携申請はありません。</div>'}

function renderMonitoringReviews(){const items=dashboard?.monitoringReviews||[];$("monitoringReviewList").innerHTML=items.length?items.map(x=>`<article class="review-card"><div class="management-head"><div><h3>${safe(x.clientName)}／${safe(D.fmtDate(x.monitoringMonth))}</h3><div class="management-meta">${safe(x.staffName)}／提出 ${safe(x.submittedAt?D.fmt(x.submittedAt):"")}</div></div><span class="badge">確認待ち</span></div><div class="review-content"><div><b>生活・心身状態</b>${safe(x.conditionSummary||"")}</div><div><b>サービス評価</b>${safe(x.serviceEvaluation||"")}</div><div><b>課題</b>${safe(x.issues||"")}</div><div><b>次の対応</b>${safe(x.nextActions||"")}</div><div><b>家族公開要約</b>${safe(x.familyPublicSummary||"")}</div></div><div class="review-actions"><textarea class="control" data-review-reason="${safe(x.id)}" placeholder="差戻し理由（差戻し時は必須）"></textarea><button class="mini-btn primary" type="button" data-monitoring-review="${safe(x.id)}" data-version="${safe(x.version)}" data-decision="approved">承認</button><button class="mini-btn danger" type="button" data-monitoring-review="${safe(x.id)}" data-version="${safe(x.version)}" data-decision="returned">差戻し</button></div></article>`).join(""):'<div class="empty">確認待ちのモニタリングはありません。</div>'}

async function runSystemCheck(){if(!token)return;try{const d=await D.api("/admin/system-check",{headers:authHeaders()}),db=d.database||{};$("healthGrid").innerHTML=[[d.version,"Worker"],[d.documentVersion||"","書類RPC"],[db.version||"","データベース"],[db.tables?.required_count??30,"必須テーブル"],[(db.tables?.missing||[]).length,"不足テーブル"],[(db.rls?.disabled||[]).length,"RLS無効"],[db.demo?.clients??0,"デモ利用者"],[db.demo?.prepared?"準備済み":"未準備","デモ基本データ"],[d.ok?"正常":"要確認","総合判定"]].map(([v,t])=>`<div class="health-item"><b>${safe(t)}</b><span>${safe(v)}</span></div>`).join("");D.hide(statusEl)}catch(err){D.show(statusEl,"error",err.message)}}

async function handleDelegatedClick(e){const cbtn=e.target.closest("[data-client]");if(cbtn){await openClient(cbtn.dataset.client);return}const isave=e.target.closest("[data-intake-save]");if(isave){const id=isave.dataset.intakeSave;try{await D.api(`/owner/intakes/${id}`,{method:"POST",headers:authHeaders(),body:JSON.stringify({status:document.querySelector(`[data-intake-status="${id}"]`).value,expectedStatus:isave.dataset.currentStatus,assignedStaffId:document.querySelector(`[data-intake-staff="${id}"]`).value,closeReason:document.querySelector(`[data-intake-close="${id}"]`).value})});await Promise.all([loadIntakes(),loadDashboard()]);D.show(statusEl,"success","相談受付を更新しました。")}catch(err){D.show(statusEl,"error",err.message)}return}
  const dload=e.target.closest("[data-document-download]");if(dload){await downloadDocument(dload);return}const dreview=e.target.closest("[data-document-review]");if(dreview){await reviewDocument(dreview);return}
  const cert=e.target.closest("[data-edit-cert]");if(cert){openCertification(cert.dataset.editCert);return}const plan=e.target.closest("[data-edit-plan]");if(plan){openPlan(plan.dataset.editPlan);return}const meet=e.target.closest("[data-edit-meeting]");if(meet){openMeeting(meet.dataset.editMeeting);return}
  const link=e.target.closest("[data-link-decision]");if(link){const id=link.dataset.linkDecision,note=document.querySelector(`[data-link-note="${id}"]`)?.value||"";try{await D.api(`/owner/link-requests/${id}/decision`,{method:"POST",headers:authHeaders(),body:JSON.stringify({decision:link.dataset.decision,decisionNote:note})});await Promise.all([loadLinkRequests(),loadDashboard()]);D.show(statusEl,"success","LINE連携申請を処理しました。")}catch(err){D.show(statusEl,"error",err.message)}return}
  const review=e.target.closest("[data-monitoring-review]");if(review){const id=review.dataset.monitoringReview,reason=document.querySelector(`[data-review-reason="${id}"]`)?.value||"";try{await D.api(`/owner/monitoring/${id}/review`,{method:"POST",headers:authHeaders(),body:JSON.stringify({decision:review.dataset.decision,returnReason:reason,expectedVersion:Number(review.dataset.version)})});await loadDashboard();renderMonitoringReviews();D.show(statusEl,"success","モニタリング記録を処理しました。")}catch(err){D.show(statusEl,"error",err.message)}}
}
})();