(()=>{"use strict";
const D=window.DPRO,c=D.config,$=id=>document.getElementById(id),statusEl=$("status"),loginPanel=$("loginPanel"),appPanel=$("appPanel");
let token=sessionStorage.getItem(D.ownerTokenKey)||"",dashboard=null;
const roleLabels={manager:"管理者",chief_care_manager:"主任ケアマネ"};
const intakeLabels={new:"新規",contacting:"連絡中",interview_scheduled:"面談予定",assessing:"アセスメント中",contracted:"契約済み",declined:"辞退",closed:"終了"};
const careLabels={independent:"自立",support_1:"要支援1",support_2:"要支援2",care_1:"要介護1",care_2:"要介護2",care_3:"要介護3",care_4:"要介護4",care_5:"要介護5",pending:"申請中",unknown:"未設定"};
const safe=v=>D.esc(v??""),label=(map,v)=>map[v]||v||"-",authHeaders=()=>({Authorization:`Bearer ${token}`});
$("version").textContent=c.version||"";$("organizationCode").value=c.organizationCode||"";
$("clearCode").addEventListener("click",()=>{$("accessCode").value="";$("accessCode").focus()});
$("demoFill").addEventListener("click",()=>{$("organizationCode").value="dpro_careplan_demo";$("staffCode").value="DEMO-MANAGER";$("accessCode").value="1234"});
$("loginForm").addEventListener("submit",login);$("logout").addEventListener("click",logout);$("refreshAll").addEventListener("click",refreshAll);$("runSystemCheck").addEventListener("click",runSystemCheck);
document.querySelectorAll(".ipad-tabs button").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view)));document.addEventListener("click",handleAction);if(token)restore();
async function login(e){e.preventDefault();const b=$("loginButton");b.disabled=true;try{const data=await D.api("/owner/login",{method:"POST",body:JSON.stringify({organizationCode:$("organizationCode").value.trim(),staffCode:$("staffCode").value.trim(),accessCode:$("accessCode").value})});token=data.token;sessionStorage.setItem(D.ownerTokenKey,token);showApp(data);await refreshAll();D.hide(statusEl)}catch(err){D.show(statusEl,"error",err.message)}finally{b.disabled=false}}
async function restore(){try{const data=await D.api("/auth/me",{headers:authHeaders()});if(!["manager","chief_care_manager"].includes(data.staff?.role_type))throw new Error("管理者・主任ケアマネ権限が必要です。");showApp(data);await refreshAll()}catch(err){sessionStorage.removeItem(D.ownerTokenKey);token="";D.show(statusEl,"error",err.message||"ログインし直してください。")}}
function showApp(data){const s=data.staff||{},o=data.organization||{};$("ownerName").textContent=s.full_name||s.fullName||"";$("ownerMeta").textContent=`${label(roleLabels,s.role_type||s.roleType)}／${s.staff_code||s.staffCode||""}`;$("organizationName").textContent=o.organization_name||o.organizationName||"";$("todayLabel").textContent=new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",dateStyle:"full"}).format(new Date());loginPanel.classList.add("hidden");appPanel.classList.remove("hidden")}
async function logout(){try{await D.api("/auth/logout",{method:"POST",headers:authHeaders()})}catch{}sessionStorage.removeItem(D.ownerTokenKey);token="";location.reload()}
function switchView(name){document.querySelectorAll(".ipad-view").forEach(v=>v.classList.add("hidden"));document.querySelectorAll(".ipad-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.view===name));const map={today:"viewToday",approval:"viewApproval",deadline:"viewDeadline",staff:"viewStaff",system:"viewSystem"};$(map[name]||"viewToday").classList.remove("hidden");if(name==="system")runSystemCheck()}
async function refreshAll(){try{dashboard=await D.api("/owner/dashboard",{headers:authHeaders()});render();D.hide(statusEl)}catch(err){D.show(statusEl,"error",err.message)}}
function render(){renderSummary();renderIntakes();renderMeetings();renderLinks();renderMonitoring();renderDeadlines();renderStaff()}
function renderSummary(){const s=dashboard?.summary||{};const items=[[s.activeClients||0,"利用中"],[s.todayAppointments||0,"本日の予定"],[s.newIntakes||0,"未完了相談","attention"],[s.pendingLinks||0,"LINE承認待ち","attention"],[s.monitoringReview||0,"記録確認待ち","attention"],[s.certificationDue||0,"認定期限90日内","critical"],[s.planDue||0,"計画見直し30日内","attention"],[s.documentDue||0,"書類期限14日内","attention"],[s.openAlerts||0,"未解決警告","critical"],[(dashboard?.upcomingMeetings||[]).length,"担当者会議"]];$("summaryGrid").innerHTML=items.map(([n,t,cl])=>`<div class="ipad-summary-card ${cl||""}"><b>${safe(n)}</b><span>${safe(t)}</span></div>`).join("");const approvals=(dashboard?.pendingLinks||[]).length+(dashboard?.monitoringReviews||[]).length;$("approvalTabCount").textContent=`${approvals}件`;$("deadlineTabCount").textContent=`${(dashboard?.deadlines||[]).length}件`}
function renderIntakes(){const items=dashboard?.recentIntakes||[];$("intakeCount").textContent=`${items.length}件`;$("intakeList").innerHTML=items.length?items.map(x=>`<article class="ipad-list-item"><div class="ipad-item-head"><div><div class="ipad-item-title">${safe(x.applicantName)}／${safe(label(intakeLabels,x.status))}</div><div class="ipad-item-meta">${safe(x.intakeCode)}／${safe(x.phone||"電話なし")}／${safe(x.assignedStaffName||"担当未設定")}</div></div><small>${safe(D.fmt(x.createdAt))}</small></div><p class="ipad-item-body">${safe((x.inquirySummary||"").slice(0,180))}</p>${x.status==="new"?`<div class="ipad-actions"><button class="ipad-action primary" type="button" data-intake-contact="${safe(x.id)}" data-current="${safe(x.status)}">連絡中にする</button></div>`:""}</article>`).join(""):'<div class="empty-ipad">新しい相談受付はありません。</div>'}
function renderMeetings(){const items=dashboard?.upcomingMeetings||[];$("meetingCount").textContent=`${items.length}件`;$("meetingList").innerHTML=items.length?items.map(x=>`<article class="ipad-list-item"><div class="ipad-item-title">${safe(x.clientName)}</div><div class="ipad-item-meta">${safe(x.scheduledStart?D.fmt(x.scheduledStart):"日時調整中")}／${safe(x.location||"場所未設定")}／${safe(x.status)}</div></article>`).join(""):'<div class="empty-ipad">今後の担当者会議はありません。</div>'}
function renderLinks(){const items=dashboard?.pendingLinks||[];$("linkCount").textContent=`${items.length}件`;$("linkList").innerHTML=items.length?items.map(x=>`<article class="ipad-list-item"><div class="ipad-item-title">${safe(x.applicantName||x.familyName||"申請者")} → ${safe(x.clientName||"利用者未照合")}</div><div class="ipad-item-meta">${safe(x.requestCode)}／${safe(x.relationship||"関係未設定")}／${safe(x.phone||"")}</div><div class="ipad-actions"><button class="ipad-action primary" type="button" data-link-decision="${safe(x.id)}" data-decision="approved">承認</button><button class="ipad-action danger" type="button" data-link-decision="${safe(x.id)}" data-decision="rejected">却下</button></div></article>`).join(""):'<div class="empty-ipad">LINE連携の承認待ちはありません。</div>'}
function renderMonitoring(){const items=dashboard?.monitoringReviews||[];$("monitoringCount").textContent=`${items.length}件`;$("monitoringList").innerHTML=items.length?items.map(x=>`<article class="ipad-list-item"><div class="ipad-item-title">${safe(x.clientName)}／${safe(D.fmtDate(x.monitoringMonth))}</div><div class="ipad-item-meta">${safe(x.staffName)}／提出 ${safe(D.fmt(x.submittedAt))}</div><p class="ipad-item-body"><b>状態：</b>${safe((x.conditionSummary||"").slice(0,220))}<br><b>評価：</b>${safe((x.serviceEvaluation||"").slice(0,220))}<br><b>次の対応：</b>${safe((x.nextActions||"").slice(0,220))}</p><div class="ipad-actions"><button class="ipad-action primary" type="button" data-monitoring-decision="${safe(x.id)}" data-decision="approved" data-version="${safe(x.version)}">承認</button><button class="ipad-action danger" type="button" data-monitoring-decision="${safe(x.id)}" data-decision="returned" data-version="${safe(x.version)}">差戻し</button></div></article>`).join(""):'<div class="empty-ipad">確認待ちのモニタリング記録はありません。</div>'}
function renderDeadlines(){const items=dashboard?.deadlines||[];$("deadlineList").innerHTML=items.length?items.map(x=>{const overdue=isPast(x.certificationValidTo)||isPast(x.nextReviewDue);return`<article class="ipad-deadline ${overdue?"overdue":""}"><div><strong>${safe(x.clientName)}</strong><small>${safe(x.clientCode)}／${safe(x.primaryStaffName||"担当未設定")}／${safe(label(careLabels,x.careLevel))}</small></div><div class="date-block">認定期限<br>${safe(x.certificationValidTo?D.fmtDate(x.certificationValidTo):"未設定")}</div><div class="date-block">計画見直し<br>${safe(x.nextReviewDue?D.fmtDate(x.nextReviewDue):"未設定")}</div></article>`}).join(""):'<div class="empty-ipad">現在、期限が近い利用者はいません。</div>'}
function renderStaff(){const items=dashboard?.staffWorkload||[];$("staffList").innerHTML=items.length?items.map(x=>`<article class="ipad-staff-card"><h2>${safe(x.fullName)}</h2><small>${safe(label(roleLabels,x.roleType))}／${safe(x.staffCode)}</small><div class="ipad-metrics"><div class="ipad-metric"><b>${safe(x.primaryClients)}</b><span>主担当</span></div><div class="ipad-metric"><b>${safe(x.openTasks)}</b><span>未完了タスク</span></div><div class="ipad-metric"><b>${safe(x.todayAppointments)}</b><span>本日の予定</span></div></div></article>`).join(""):'<div class="empty-ipad">職員情報がありません。</div>'}
function isPast(v){if(!v)return false;const end=new Date(String(v)+"T23:59:59+09:00");return end.getTime()<Date.now()}
async function handleAction(e){const link=e.target.closest("[data-link-decision]");if(link){await decideLink(link);return}const mon=e.target.closest("[data-monitoring-decision]");if(mon){await decideMonitoring(mon);return}const intake=e.target.closest("[data-intake-contact]");if(intake)await markContacting(intake)}
async function decideLink(btn){const decision=btn.dataset.decision;let note="";if(decision==="rejected"){note=prompt("却下理由を入力してください。")||"";if(!note)return}if(!confirm(decision==="approved"?"このLINE連携申請を承認しますか。":"このLINE連携申請を却下しますか。"))return;btn.disabled=true;try{await D.api(`/owner/link-requests/${btn.dataset.linkDecision}/decision`,{method:"POST",headers:authHeaders(),body:JSON.stringify({decision,decisionNote:note})});await refreshAll();D.show(statusEl,"success",decision==="approved"?"LINE連携を承認しました。":"LINE連携申請を却下しました。")}catch(err){D.show(statusEl,"error",err.message)}finally{btn.disabled=false}}
async function decideMonitoring(btn){const decision=btn.dataset.decision;let reason="";if(decision==="returned"){reason=prompt("差戻し理由を入力してください。")||"";if(!reason)return}if(!confirm(decision==="approved"?"このモニタリング記録を承認しますか。":"この記録を差し戻しますか。"))return;btn.disabled=true;try{await D.api(`/owner/monitoring/${btn.dataset.monitoringDecision}/review`,{method:"POST",headers:authHeaders(),body:JSON.stringify({decision,returnReason:reason,expectedVersion:Number(btn.dataset.version)})});await refreshAll();D.show(statusEl,"success",decision==="approved"?"モニタリング記録を承認しました。":"モニタリング記録を差し戻しました。")}catch(err){D.show(statusEl,"error",err.message)}finally{btn.disabled=false}}
async function markContacting(btn){if(!confirm("この相談受付を「連絡中」に更新しますか。"))return;btn.disabled=true;try{await D.api(`/owner/intakes/${btn.dataset.intakeContact}`,{method:"POST",headers:authHeaders(),body:JSON.stringify({status:"contacting",expectedStatus:btn.dataset.current,assignedStaffId:null,clientId:null,closeReason:null})});await refreshAll();D.show(statusEl,"success","相談受付を「連絡中」に更新しました。")}catch(err){D.show(statusEl,"error",err.message)}finally{btn.disabled=false}}
async function runSystemCheck(){const b=$("runSystemCheck");b.disabled=true;try{const [health,check]=await Promise.all([D.api("/health"),D.api("/admin/system-check",{headers:authHeaders()})]);const db=check.database||{};const cards=[[health.ok,"Worker",health.version],[health.dbOk,"データベース",health.databaseVersion],[health.authOk,"認証RPC",health.authVersion],[health.memberOk,"家族RPC",health.memberVersion],[health.staffOk,"ケアマネRPC",health.staffVersion],[health.ownerOk,"管理者RPC",health.ownerVersion],[health.documentOk,"書類RPC",health.documentVersion],[(db.tables?.missing||[]).length===0,"不足テーブル",`${(db.tables?.missing||[]).length}件`],[(db.rls?.disabled||[]).length===0,"RLS無効",`${(db.rls?.disabled||[]).length}件`]];$("systemGrid").innerHTML=cards.map(([ok,t,v])=>`<div class="system-card ${ok?"ok":"ng"}"><strong>${safe(t)}</strong><span>${safe(v||"-")}</span></div>`).join("");$("systemDetail").textContent=JSON.stringify({health,database:db},null,2);D.hide(statusEl)}catch(err){D.show(statusEl,"error",err.message)}finally{b.disabled=false}}
})();